### ISSUE TITLE
Error in cbind(parent, t(apply(parent, 1, fn))) :    number of rows of matrices must match (see arg 2)

### ISSUE THREAD

**Issue by ardhendujy** [hannes101/LeeStrazicichUnitRoot#2]
library(nsga2R)

fun <- function(w)
{
  y <- read.csv("C:/Users/admin/Desktop/2018/Book1.csv")
  y1 <- 1:13
  for(i in 1:13)
  {    
    y1[i] =  mean(y[,i])
    
  }
  w1=0
  for(i in 1:13)
  {
    w1 = w1+ w[i]
  }
  v1 = 0
  v2 = 0
  v3 = 0
  gamma = 1.4
  for(i in 1:ncol(y))
  {
    v1 = v1 + y1[i]*w[i]/w1 
    
  }
  
  g = ((1+v1)^(1-gamma))/(1-gamma)
  
  
  
  z =  - g

  return(z)
}
results <- nsga2R(fn= fun, varNo=13 , objDim= 2, lowerBounds = rep(0,13), upperBounds = rep(1,13),
                  popSize = 70, tourSize = 2, generations = 20, cprob = 0.7, XoverDistIdx = 5,
                  mprob = 0.2, MuDistIdx = 10)
print(results)
print(results$objectives)
I am getting above error in above code. Can you help?

**Comment by hannes101** [comment]
For such a problem there are better places to ask for help. I suggest to create an account at https://stackoverflow.com/ and provide a minimal working example. Especially provide exemplary data for your y variable.
I did not check any of the code, since I got not an awful lot of time at the moment.
